services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "${ORACLE_PORT}:1521"
    volumes:
      - ${ORACLE_VOLUME}:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s ${ORACLE_USERNAME}/${ORACLE_PASSWORD}@localhost/${ORACLE_DATABASE}"]
      interval: 30s
      timeout: 10s
      retries: 10

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_VOLUME}:/data/db

volumes:
  oracle_data:
  mongo_data:
