server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${ORACLE_USERNAME:userdb}
    password: ${ORACLE_PASSWORD:userdb_password}
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongo_user}:${MONGO_PASSWORD:mongo_pass}@localhost:27017/${MONGO_INITDB_DATABASE:userlogs}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  config: classpath:logback-spring.xml
  file:
    path: logs
