server:
  port: ${EUREKA_SERVER_PORT:8081}

spring:
  application:
    name: user-service
    version: 1.0.0

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: ${ORACLE_USERNAME:userdb}
    password: ${ORACLE_PASSWORD:userdb_password}
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongo_user}:${MONGO_PASSWORD:mongo_pass}@localhost:27017/${MONGO_INITDB_DATABASE:userlogs}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:demo.demo0202s@gmail.com}
    password: ${MAIL_PASSWORD:euuhhgmasktovxkp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/

#jwt:
#  secret: dGhpc2lzYXNlY3VyZXRlc3RrZXlmb3Jqd3RzaWduYXR1cmVhdXRoZW50aWNhdGlvbmFuZGF1dGhvcml6YXRpb24  # use the full Base64 string here
#  expiration-ms: 3600000



logging:
  level:
    com.bank.user: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  config: classpath:logback-spring.xml
  file:
    path: logs
  pattern:
    console: "%5p[${spring.application.name}],[${spring.application.instance_id},%X{traceId},%X{spanId}] %m%n"