server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/${MONGO_INITDB_DATABASE}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

