spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${EUREKA_USERNAME:eureka}
      password: ${EUREKA_PASSWORD:password}

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${SERVER_PORT:8761}
    status-page-url: http://${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/actuator/info
    health-check-url: http://${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/
  server:
    enable-self-preservation: ${SELF_PRESERVATION_ENABLED:true}
    eviction-interval-timer-in-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml
  file:
    path: logs